10 INPUT "PREIS JE KILO FARBE EINGEBEN: ";KP
20 INPUT "KILO JE QUADRATMETER EINGEBEN: ";KQ
30 PRINT
40 INPUT "LAENGE EINGEBEN: ";L
50 INPUT "BREITE EINGEBEN: ";B
60 F=L*B
70 M=F*KQ
80 P=M*KP
90 PRINT
100 PRINT "FUER DIE FLAECHE VON ";F;" QM"
110 PRINT "WERDEN ";M;" KILO FARBE BENOETIGT."
120 PRINT "DER PREIS FUER DIESE ";M;" kg FARBE BETRAEGT ";P;" EUR:"
124 INPUT "WOLLEN SIE NOCH EINE NEUE FLAECHE BERECHNEN ";W$
125 IF W$="JA" THEN GOTO 30
126 PRINT "AUF WIEDERSEHEN"
130 END
